### ISSUE TITLE
The administration dashboard is ugly.

### ISSUE THREAD

**Issue by LookACastle** [TheRacetrack/racetrack#124]
The buttons should be right aligned.

There should be some amount of padding between the lines so the buttons don't blend into each other.

**Comment by JosefAssadERST** [comment]
I think you could put it in a bootstrap layout with columns.

But more broadly, I think also the plugins stuff above could be tightened up considerably.

![image](https://user-images.githubusercontent.com/63641218/212063172-8985e819-6881-4485-944e-e6cb808e8bc3.png)

Could have for example something like 

![image](https://user-images.githubusercontent.com/63641218/212063635-654799fc-f893-4f22-931f-af42e0d49bde.png)

Look what you made me do. You made me use Paint.

**Comment by LookACastle** [comment]
I'm a little confused as to what your drawing is trying to convey - particularly, what are the items you want listed?

```
Kubernetes:
    - //What goes here?
    - //Or here?
```

**Comment by JosefAssadERST** [comment]
The way RT currently works: RT itself is useless and does nothing (as pointed out by the lead developer @iszulcdeepsense ). Fortunately, this situation can be remedied with plugins. Infrastructure plugins provide the ability to deploy fatmen to different infrastructure *types*. Note, *types*. Just installing the k8s plugin isn't enough, because you then have to define one or more *instances* of that *type* of infrastructure, e.g. `gcp-2.google.kr` or `hello.k8s.org`.

Right now all that information is there, but it's a flat list. It might be easier to parse if put in a list with a sublist:

```
k8s:
    gcp.google.kr
    hello.k8s.org
docker:
    meow.cats.biz
    thor.istired.of-hammer-jokes.com
```

That is a _little_ better than Irek's current design, which suggests he owns stock in a company making eyeglasses.

You might have an even better idea for how to represent currently installed infrastructure types and instances than that. That's just simple and a bit better.

**Comment by iszulcdeepsense** [comment]
Closing as it's supposed to be closed after merging https://github.com/TheRacetrack/racetrack/pull/135

@LookACastle Next time, please click "Create a branch" on the right side of the issue so it's linked with the Merge request or link it manually.
