### ISSUE TITLE
When a Job is in state "Lost", you can still click "open" and it gives a white page of death

### ISSUE THREAD

**Issue by JosefAssadERST** [TheRacetrack/racetrack#133]
* Why are they actually ending up in that state?
* If the Fatman is lost, we probably should deactivate the open button
* People might have bookmarked the page you get when you "Open" a fatman. If they have and it gets lost, they just see the white page of death with no context or explanation. Should we show a custom error page or a 404 or what?

**Comment by iszulcdeepsense** [comment]
> Why are they actually ending up in that state?

"Lost" means it's in the database records, but it's not in the cluster. In other words, it's when a workload is supposed to be here, but the liveness probes prove that it's no longer there.
For instance, you've had a workload, but someone wiped it out from kubernetes manually.
Another example: you've got a docker daemon. It presents you the running container when doing `docker ps` on port 22, but this container runs on port 7000, which is blocked by firewall and can't be reached by Racetrack's live-checks, so it thinks someone deleted it.

> If the Fatman is lost, we probably should deactivate the open button

A bit of historical background: Once the "Open" button was in fact being hidden as a result of "Lost" state, but that introduced other unwanted behaviors so I changed that back.
Refreshing the status happens in background every minute, so there's a chance that your slotcar is really running, while the status is still Lost (due to some weird reasons that might be a subject of another issues) and now you need to wait a minute until "Open" button appears.

> Should we show a custom error page or a 404 or what?

I agree. In case of Lost status, PUB should show some error instead of blank page.

**Comment by JosefAssadERST** [comment]
> "Lost" means it's in the database records, but it's not in the cluster

Ah right. That's in the docs somewhere right?

When that occurs do we currently actually do anything? I mean like try to recreate it actively? I realise it could be a networking partition which we can't do much about it, just thinking what our current behavior is if any.

I'm guessing we do nothing and leave the active recreation to the user via the "Reprovision" action?

> Once the "Open" button was in fact being hidden as a result of "Lost" state, but that introduced other unwanted behaviors so I changed that back

What were those behaviors? It just seems orthogonal to me, if a fatman is lost we don't tease the user with an active "Open" button.

**Comment by iszulcdeepsense** [comment]
> Ah right. That's in the docs somewhere right?

not really. It's only in the docstrings in the code. Do you think we need some document explaining how to use a Dashboard?

> When that occurs do we currently actually do anything? I mean like try to recreate it actively?

There's reconciliation loop trying to restore the order.

> What were those behaviors? It just seems orthogonal to me

Indeed, it's orthogonal. Few times I've run into an issue about Racetrack wrongly claiming "Lost" status, while the job was really running. 
I think there's a chance for a race condition when the background thread finds the newly created Pod, while it's in the middle of deployment and it's not ready yet, so it claims it to be Lost. Not sure if this still occurs, I need to explore that.
Thus, "Open" button should be hidden and the wrong "Lost" status should be solved in https://github.com/TheRacetrack/racetrack/issues/134.
