### ISSUE TITLE
Online editing of job manifest

### ISSUE THREAD

**Issue by jsandroos** [TheRacetrack/racetrack#217]
The Lab expressed that it would be nice to be able to edit the manifest of a job directly in the RT dashboard and then redeploy the job with the updated manifest.

Let's discuss pros and cons of this functionality.

**Comment by iszulcdeepsense** [comment]
I think that's a good idea as long as we're fine with sacrificing Infrastructure-as-Code. The consequences are:
- your online changes can be overwritten accidentally by a local deployment.
- If the job is wiped out for some reason, nobody really knows what exactly was deployed there, can't recover the exact revision.
- The history of changes is hard to track without git.

Nevertheless, If we use common sense, I consider this feature beneficial. We don't need to drop Infrastructure-as-Code completely.
Fast prototyping and temporary experiments could be made online, while keeping in mind that it should get reflected in git after all.

**Comment by LookACastle** [comment]
I feel like such jobs should quite obviously be marked in the dashboard as lesser somehow - preferably in bright red so that people don't fix something in a way that isn't properly infrastructure-as-code. I want to nudge people in the direction of not using online changes to get something up and running in production. Something like this (but prettier) I think could work: 
![2023-03-20_14-02](https://user-images.githubusercontent.com/15412127/226347387-325131cf-67e2-469a-bbc1-f2413f477e6f.png)


It'd be really nice not to have an issue created sometime in the future because someone's jobs got wiped and no one can get them back up and running. A big red warning sign would help, I think.

**Comment by JosefAssadERST** [comment]
Well this church needs a heretic.

Alternative proposal:

1. Stop sending job.yaml from racetrack client
2. Send instead a command to deloy which contains only instructions for fetching the git remote (including branch)
3. Obtain the job.yaml from the git remote
4. Poll the git remote for changes and redeploy automatically when there's new commits on the specified branch

In other words, gitops.

This way we don't have a sync problem.

If someone edits the job.yaml in the dashboard, it gets pushed back to the tip of the branch. Maybe even people will prefer to not edit in the web UI since the development loop becomes tighter.

I'm mainly dissenting to force some deeper thinking on this proposed change, but that doesn't mean I don't belive in this alternate idea.

**Comment by LookACastle** [comment]
I think there's a lot of value in being able to throw code onto the wall and seeing what sticks. Having a giant commit history because someone didn't know what they were doing and just tried 20 different things until one worked could be a bother to some people.

My own little heresy that I've been growing in my backyard revolves around implementing proper gitops, but being able to freeze it somehow for a small period of time - or freeze it in some way that's generally disruptive and _has_ to be reconciled before normal operation can continue. I'm not sure about how this would work on a detailed level - but I am sure that I really wanna discourage people from using this web editor to do anything more than testing. Real development should live in git.

It's however an unfinished thought, and I think it'd be a lot more work than slapping an "out of sync" label on the Job - something which I think is valuable regardless.
