### ISSUE TITLE
Racetrack get remote - nonverbose version

### ISSUE THREAD

**Issue by Koshmaar** [TheRacetrack/racetrack#374]
Currently when user types `racetrack get remote` he will see result designed for human:
> [2023-11-15 19:00:52] INFO  Current remote is "compose" - http://127.0.0.1:7102/lifecycle

But I think it would be useful to get just the address, so that it can be used in scripts, in the same way as `racetrack get auth-token`. For example, that would improve the testing scripts by making them work wherever RT is deployed (localhost, compose, kind, remote k8s):

> perform:
> 	curl -X POST \
> 		"http://localhost:7000/pub/job/tomcat-adder/latest/api/v1/perform" \
> 		-H "Content-Type: application/json" \
> 		-d '{"numbers": [40, 2]}'
> 

In this case actually, the `localhost:7000/pub` part would be replaced. So it's not remote as indicated above, but additonal thing. To summarise, my proposition:
`racetrack get remote --short` -> http://127.0.0.1:7102/lifecycle
`racetrack get remote-pub --short` ->  http://127.0.0.1:7105/pub

(the exact values will of course depend on the current remote; and instead of `remote-pub` it could also be called just `pub`)

**Comment by iszulcdeepsense** [comment]
# Lifecycle URL

+1 for the idea.

I think the most common convention in Command-line interfaces is to provide `-q` or `--quiet` flag to reduce verbosity.
Verbose command `racetrack get remote` shows 2 things right now: current alias, and the full URL it resolves to. Let's keep it as a default.
Then `racetrack get remote -q` would return just `http://127.0.0.1:7102/lifecycle`

# Pub URL

However, when it comes to Pub address, it's not that easy. Racetrack client can't tell what's the Pub address, since the only address it has in its config is Lifecycle URL.
Let's take a few examples. It's hard to find a pattern:
- On docker setup: **Lifecycle** at `http://127.0.0.1:7102/lifecycle`, **Pub** at `http://127.0.0.1:7105/pub` - they differ in port and path
- On kind setup: **Lifecycle** at `http://127.0.0.1:7002/lifecycle`, **Pub** at `http://127.0.0.1:7005/pub` - they differ in port and path
- On dedicated Kubernetes cluster: **Lifecycle** at `https://hubernetes.example.com/lifecycle`, **Pub** at `https://hubernetes.example.com/pub` - they differ in path
- On standalone host: **Lifecycle** at `http://1.2.3.4:7102/lifecycle`, **Pub** at `http://1.2.3.4:7105/pub` - they differ in port and path

Sometimes the URLs differ in path and sometimes in ports as well (and this transformation is not obvious).

Solutions:

1. A heuristic algorithm - Do the following to build Pub URL:
   - rename `/lifecycle` path to `/pub`
   - if port is 7002, turn it into 7005
   - if port is 7102, turn it into 7105

2. As a Racetrack's hub, Lifecycle would direct clients to other services.
   It would serve corresponding Pub's address in its `/health` or `/status` endpoint.
