### ISSUE TITLE
Download button sometimes work, sometimes it doesn't.

### ISSUE THREAD

**Issue by anders314159** [TheRacetrack/racetrack#490]
Clicking the download button on plugins sometimes give "default backend - 404", and sometimes it actually downloads the plugin.

**Comment by anders314159** [comment]
It works in docker, kind, but on the clusters.

**Comment by iszulcdeepsense** [comment]
My guess is that it breaks with multiple replicas. I suppose you tried to download the plugin right after uploading it. There's a chance that one replica of Lifecycle already got it, but the others didn't notice it, didn't load it yet and returned 404 (since services are load balanced with round robin strategy the next request could have been handled by different replica).
Anyways, replicas share the same persistent volume, so the possible solution would be to check if the file exists on a shared disk, if the plugin wasn't found in a Lifecycle's memory in first place.

**Comment by iszulcdeepsense** [comment]
Or now I see it might be something different.
The problem is with the wrong URL:
https://ikp-rt.example.com/api/v1/plugin/kubernetes-infrastructure/1.5.1/download
while it should be prefixed with the name of a service:
https://ikp-rt.example.com/lifecycle/api/v1/plugin/kubernetes-infrastructure/1.5.1/download

**Comment by anders314159** [comment]
Yeah, so it worked locally because the local url is http://127.0.0.1:7103/, where the port is lifecycle. The download button then creates a link that includes the port http://127.0.0.1:7103/api/v1/plugin/kubernetes-infrastructure/1.5.1/download.

If you do the same on the cluster, there's no port, so the request does not hit lifecycle, and it needs /lifecycle prepended to the link.
