### ISSUE TITLE
Move initial job health check to infrastructure plugins.

### ISSUE THREAD

**Issue by anders314159** [TheRacetrack/racetrack#537]
In [lifecycle/lifecycle/monitor/monitors.py](https://github.com/TheRacetrack/racetrack/blob/master/lifecycle/lifecycle/monitor/monitors.py#L30) Racetrack calls the infrastructure targets own monitoring. For the K8s plugin, that is [src/monitor.py](https://github.com/TheRacetrack/plugin-kubernetes-infrastructure/blob/master/src/monitor.py#L27). A big part of `KubernetesMonitor` is calling [check_until_job_is_operational](https://github.com/TheRacetrack/plugin-kubernetes-infrastructure/blob/master/src/monitor.py#L109), which is imported from [lifecycle/lifecycle/monitor/health.py](https://github.com/TheRacetrack/racetrack/blob/master/lifecycle/lifecycle/monitor/health.py#L10).

I propose moving the bulk of the initial monitoring from lifecycle/lifecycle/monitor/health.py to the infrastructure targets themselves. This would allows the K8s infrastructure target to check for K8s specific errors, while still querying the /live and /ready endpoints.

In general, this allows more flexibility for the infrastructure targets to terminate deployments early if something goes wrong, thereby speeding up development for Racetrack users, but it also puts the onus on the infrastructure targets to check /live and /ready, which would lead to a bit of code duplication across plugins.

@iszulcdeepsense
@JosefAssad - who's the new architect so I can ping them?

**Comment by iszulcdeepsense** [comment]
It makes sense. I'd move this issue to https://github.com/TheRacetrack/plugin-kubernetes-infrastructure if you don't mind since it's plugins responsibility to stop calling the generic health checker from Racetrack core.
I think it may even work fine to work with infrastructure plugins like that:
By default, you can call the health checker from Racetrack to keep the plugin simple. But if you want something more specific, copy it and adjust the code for your needs.

**Comment by JosefAssad** [comment]
> who's the new architect so I can ping them?

Ah, no idea... Sorry.

**Comment by anders314159** [comment]
Moved to https://github.com/TheRacetrack/plugin-kubernetes-infrastructure/issues/26
